export const typeColors: Record<string, string> = {
  normal: "bg-pokemon-normal text-white",
  fire: "bg-pokemon-fire text-white",
  water: "bg-pokemon-water text-white",
  electric: "bg-pokemon-electric text-black",
  grass: "bg-pokemon-grass text-white",
  ice: "bg-pokemon-ice text-black",
  fighting: "bg-pokemon-fighting text-white",
  poison: "bg-pokemon-poison text-white",
  ground: "bg-pokemon-ground text-white",
  flying: "bg-pokemon-flying text-white",
  psychic: "bg-pokemon-psychic text-white",
  bug: "bg-pokemon-bug text-white",
  rock: "bg-pokemon-rock text-white",
  ghost: "bg-pokemon-ghost text-white",
  dragon: "bg-pokemon-dragon text-white",
  dark: "bg-pokemon-dark text-white",
  steel: "bg-pokemon-steel text-black",
  fairy: "bg-pokemon-fairy text-white",
};
